# Generated by Django 6.0.1 on 2026-02-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_address_options_alter_country_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='useraddress',
            index=models.Index(fields=['user', 'is_default'], name='accounts_us_user_id_7fa4e4_idx'),
        ),
        migrations.AddIndex(
            model_name='useraddress',
            index=models.Index(fields=['user', 'address'], name='accounts_us_user_id_937542_idx'),
        ),
        migrations.AddIndex(
            model_name='userpaymentmethod',
            index=models.Index(fields=['user', 'is_default'], name='accounts_us_user_id_10cc1e_idx'),
        ),
    ]
