# Generated by Django 6.0.1 on 2026-02-04 02:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_shoppingcart_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shoppingcart',
            index=models.Index(fields=['session_id'], name='cart_shoppi_session_9a323c_idx'),
        ),
    ]
