# Generated by Django 6.0.1 on 2026-01-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderline',
            options={'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelOptions(
            name='shoporder',
            options={'verbose_name': 'Shop Order', 'verbose_name_plural': 'Shop Orders'},
        ),
        migrations.AlterField(
            model_name='orderline',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
