# Generated by Django 6.0.1 on 2026-02-04 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderline_options_alter_shoporder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporder',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='shipping_carrier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shoporder',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
