# Generated by Django 6.0.1 on 2026-02-04 02:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_useraddress_accounts_us_user_id_7fa4e4_idx_and_more'),
        ('orders', '0003_shoporder_delivered_at_shoporder_shipped_at_and_more'),
        ('products', '0007_product_products_pr_is_publ_95a232_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='orderline',
            index=models.Index(fields=['order', 'product_item'], name='orders_orde_order_i_b1c534_idx'),
        ),
        migrations.AddIndex(
            model_name='shoporder',
            index=models.Index(fields=['user', 'order_date'], name='orders_shop_user_id_1c5015_idx'),
        ),
        migrations.AddIndex(
            model_name='shoporder',
            index=models.Index(fields=['order_status', 'order_date'], name='orders_shop_order_s_17d4ae_idx'),
        ),
        migrations.AddIndex(
            model_name='shoporder',
            index=models.Index(fields=['user', 'order_status', 'order_date'], name='orders_shop_user_id_acdd8e_idx'),
        ),
    ]
