# Generated by Django 6.0.1 on 2026-02-04 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderline_orders_orde_order_i_b1c534_idx_and_more'),
        ('products', '0008_postgres_search_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='line_delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='line_shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='line_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='orders.orderstatus'),
        ),
        migrations.AddIndex(
            model_name='orderline',
            index=models.Index(fields=['order', 'line_status'], name='orders_orde_order_i_0094a0_idx'),
        ),
    ]
