# Generated by Django 6.0.1 on 2026-02-04 02:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_is_published'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_published', 'category'], name='products_pr_is_publ_95a232_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['seller', 'category'], name='products_pr_seller__6c2fef_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['category_name'], name='products_pr_categor_a36ff0_idx'),
        ),
        migrations.AddIndex(
            model_name='productconfiguration',
            index=models.Index(fields=['product_item', 'variation_option'], name='products_pr_product_b0408f_idx'),
        ),
        migrations.AddIndex(
            model_name='variationoption',
            index=models.Index(fields=['variation', 'value'], name='products_va_variati_291fa1_idx'),
        ),
    ]
